### ISSUE TITLE
I am getting this error:

### ISSUE THREAD

**Issue by JackNotTaken** [terrychou/iVim#29] opened 2017-11-30 09:43 UTC
Every time I press i for 'insert mode', the following message appears:

Error detected while processing function InsertStatuslineColor:
E254: Cannot allocate colour DarkYellow
Press ENTER or type command to continue

I, then pressed something and I can continue to edit as normal.  The colour of the -- INSERT -- indicator is blue instead of DarkYellow.  Everything else runs smoothly.

For your info.   Note I am using  'salarized' colorscheme.

**Comment by terrychou** [comment] 2017-12-01 02:47
This happens because iVim isn't providing color value for 'DarkYellow' right now.
It will be added.

**Comment by terrychou** [comment] 2017-12-01 05:33
It is wired that I am not having this problem while using the color scheme provided above.

**Comment by JackNotTaken** [comment] 2017-12-01 11:21
[Archive.zip](https://github.com/terrychou/iVim/files/1521365/Archive.zip)
I just uploaded compressed version of vim colorscheme, also included in my vimrc.  But as mentioned I always use solarized.  The other two, however, lucius and zenburn are also installed.  Just mentioning, don't know if this has an effect or not.

**Comment by JackNotTaken** [comment] 2017-12-01 12:09
Also this is what it looks like:

[IMG_0083.JPG.zip](https://github.com/terrychou/iVim/files/1521524/IMG_0083.JPG.zip)

**Comment by terrychou** [comment] 2017-12-02 02:25
could you provide your .vimrc? I suspect that it may be the differences in configuration cause the different results.

**Comment by JackNotTaken** [comment] 2017-12-02 03:31
You may be write.  I have inspected my vimrc and it included a line setting the status line colour.  Attached is my vimrc file.  Should I replaced the DarkYellow to just Yellow?  Please advice.
[vimrc.txt.zip](https://github.com/terrychou/iVim/files/1523532/vimrc.txt.zip)

**Comment by JackNotTaken** [comment] 2017-12-02 03:32
By the way this is the same vimrc I also used in my desktop mac-mini.  But never encountered an error.

**Comment by terrychou** [comment] 2017-12-02 03:43
It is nothing wrong with using "DarkYellow", since it is a common color name mentioned in vim's documentation. As I mentioned above, this problem is probably caused by the lack of color value for this name in iVim. I am just needing to reproduce your problem to see whether my modification fixes it or not. (You could try replace "DarkYellow" with "Yellow", to confirm this, too.)

**Comment by terrychou** [comment] 2017-12-02 04:09
Yes, it is caused by the missing "DarkYellow" value. And it's been fixed now. You could edit your link to your vimrc file if you care about the privacy.

**Comment by JackNotTaken** [comment] 2017-12-02 08:56
Thanks.

**Closed** 2017-12-22 05:03 UTC
