### ISSUE TITLE
Feature Request: show “bookmarked” directories from other apps in netrw (iOS 13)

### ISSUE THREAD

**Issue by mon10a** [terrychou/iVim#69] opened 2019-06-22 17:32 UTC
I understand that iOS 13 will allow an app to bookmark an entire folder from another app, effectively granting permission to read and edit all the files in that folder. I have heard that iA Writer, Working Copy, and Scriptable already have this ability under iOS 12. 

Would it be possible to add this to iVim and have the folder/directory appear in netrw?

Benefits:

1) if you choose a folder from an app that backs up to iCloud, then all the documents you edit or create in the folder using iVim will also be backed up and synced to all your devices without having to add iCloud syncing to iVim itself;

2) more easily share documents with another app; 

3) more flexible for opening documents than the current (excellent) idocuments command.

Thanks for considering this request. 

mon10a

**Comment by ericweir** [comment] 2019-06-24 19:19
Glad to hear about this. It seems the minimum if, as Apple apparently hopes, the iPad is to become a useable work computer. Hope Terry's answer is in the affirmative.

**Comment by terrychou** [comment] 2019-06-25 07:35
Is this issue #43 we are talking about here?

**Comment by mon10a** [comment] 2019-06-25 15:02
Terry, I apologize for missing the changes you made in response to issue 43. The document picker that appears when I use :idoc does allow me to select a folder and then open it. And when I do that the contents in the folder appear in netrw and I can open and edit any of the plain text files there. So far, so good. 

Nice implementation. Thank you.

It would be even better if I could make the shared/selected folder the current working directory (e.g. :cd %:h and then :cd - to change back to the home directory when necessary). This would have at least 2 benefits:

1) make the buffer list more readable
2) make it easier to navigate in netrw between the shared folder and other directories in the iVim space.

It would also be great if I could set a global bookmark in a file in the shared folder (mA, for example) and have that bookmark work from iVim session to iVim session. Currently that only seems works while iVim is still in memory. 

My (imperfect) understanding of the changes coming in iOS 13 and iPadOS 13 is that the sharing of folders will be persistent. I think that means that the files in the shared folder should no longer be sandboxed to the app that has been granted provileges to that folder. Hopefully, the changes I request will be possible at that time.

Thanks again.

mon10a

**Comment by terrychou** [comment] 2019-06-26 07:12
1) current working directory for opened folder

It actually will :lcd into the opened folder.

2) bookmarks lost problem

Yes, since auto-restore is implemented based on vim's session, all the bookmarks will be lost in another iVim session. I will give it a consideration.

**Comment by mon10a** [comment] 2019-07-04 20:10
Sorry, I do not see how :lcd helps. After :lcd, :buffers still shows the file name only after full (very long) paths, which are hard to read.

**Comment by emkayonline** [comment] 2019-09-05 17:55
> since auto-restore is implemented based on vim's session, all the bookmarks will be lost in another iVim session

Thank you for explaining that. I was wondering why returning to iVim (even after a few minutes), my buffers would all be empty and point to an "unknown" directory. 

Doing :idoc again and selecting the folder resolves this issue, but it would be great if idoc opened the directories as bookmarks so that they could always be referenced, even when restoring a session. This article may be of help, though I'm afraid helping with the coding is beyond me.

https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories

**Comment by terrychou** [comment] 2019-09-09 07:42
@emkayonline rather than document bookmarks for remembering , the "bookmarks" was being talked about there meant the "position marks" of vim (":help marks").

The "auto-restore" feature is supposed to handle the condition you describe above. But it is hard to tell the real problem from your description. A screenshot would be more helpful.

**Comment by emkayonline** [comment] 2019-09-09 13:02
@terrychou Thank you. After reading your comment this morning I have been trying various combinations of actions to find a reproducible example. 

It seems that my issue occurs when a file (that is open in iVim) is edited in another app (even if no changes have been made in iVim). 

I am using iA Writer, but also iVim for complex text manipulations. The steps to reproduce the issue are:

1) :idoc to open an iA Writer directory in iVim. Then select a file from this directory using netrw 
2) Edit that file in iA
3) Returning to iVim: the buffer is now empty and the connection to the original file is lost

Hope this helps. If you need any more information let me know,

Martin

**Comment by terrychou** [comment] 2019-09-12 03:43
@emkayonline OK, I will look into it.

**Comment by terrychou** [comment] 2019-09-14 01:51
@emkayonline It was indeed a bug. And it's been fixed. The fix will be included in the upcoming update.

**Comment by terrychou** [comment] 2019-09-30 01:31
Version 1.53 is now available in App Store. The "document-disappearing" problem should be fixed.

Also, it includes support of viminfo file, which means information such as file marks will be restored too. Its behavior can be customized via the option 'viminfo'.

**Comment by emkayonline** [comment] 2020-01-13 20:41
Regarding the original feature request: show “bookmarked” directories from other apps in netrw (iOS 13) 

I think this is covered by the new parameter dir to idoc, ie. the command
:idoc dir

Perhaps this ticket can be closed, unless I'm missing another feature that this doesn't cover.

**Closed** 2020-01-14 04:42 UTC
