### ISSUE TITLE
Share sheet functionality broken in ipadOS 13

### ISSUE THREAD

**Issue by qqquwu** [terrychou/iVim#76] opened 2019-10-15 16:27 UTC
When I share a file via share sheet to iVim, it doesn’t open the file in iVim but rather just pops up a dialog box with “Post” as an option.

**Comment by terrychou** [comment] 2019-10-16 01:50
It looks like you were sharing text rather than a file, and it works so in that case. Since you mention "iPadOS 13", do you have the same behavior on a different iOS version?

**Comment by furuki328** [comment] 2019-12-15 04:12
I found same trouble. I share a text file from Files app. then “Post” dialog pops up, and tap “done” with no input starts iVim without the text file.

**Comment by terrychou** [comment] 2019-12-17 02:16
The "Share with iVim" option is supposed to be used to share selected text (`:help share-with-ivim`). If you want to open a file in iVim, please use "Open in iVim" or the ex command `:idocuments` instead.

**Comment by mchalkley** [comment] 2019-12-17 12:20
Something seems to have changed that has broken the “Open In” functionality.  I primarily use it with Working Copy, where it has always worked flawlessly.  I thought that perhaps Working Copy had changed something, but I can use its “Open In” with other apps, like GoCoEdit, just like I previously used iVim.  With iVim, however, I get the “Post” popup window, whether I tap the Share button, then immediately select iVim from the top list, or pick “Open in” and select iVim from there.

So it does appear that something changed with iVim when the :documents functionality was added, or around then, I’m not sure - I just hadn’t reported it before.

**Comment by terrychou** [comment] 2019-12-18 02:34
I have tried myself.

In the share sheet of iOS 13, the item "iVim" is actually "Share with iVIm". If it isn't visible, there may be the item "Open in iVim" or "Copy to iVim" available after you tap the "more" option. That is the old friend and they work as always.

**Comment by furuki328** [comment] 2019-12-18 11:53
Thank you! I’ve found it. And that works.

**Comment by mchalkley** [comment] 2019-12-18 13:18
I’m still unable to get it to work.  Every option available to me causes a dialog box that allows me to “Post” to iVim.  I’m discussing it with Anders, the creator of Working Copy now.  His comment so far (and he sent me a screenshot to demonstrate) is that “Open in iVim” is the option I’m looking for.  Why it’s not available (I only see “iVim”), is still a mystery.  I’ll update the results of my research here...

**Comment by mchalkley** [comment] 2019-12-18 15:14
Well, the only thing we’ve been able to confirm is that the “Open in iVim” option doesn’t appear on either of my iPads or my iPhone.  The option that just shows “iVim” does, but this opens a dialog box that offers the “Post” option, which just opens an empty iVim buffer.  I’m researching ways to reset this - it may come down to uninstalling and reinstalling iVim.  I’m hoping not to have to do that, but we’ll see - if anyone else has an ideas, I’d love to hear them...

**Comment by terrychou** [comment] 2019-12-19 00:43
Can you describe your steps in details? Let me see if I can find any clue.

**Comment by mchalkley** [comment] 2019-12-19 03:46
After conferring with Anders (Working Copy), he noticed that he had two “Share sheet” items for iVim.  One of them is labeled just “iVim” and, when chosen, provides the “Post” dialog (picture of it on my iPad attached).  The other is labeled “Open in iVim” and it opens iVim with the current file in a buffer, and returns the edited file to Working Copy when saved.  The latter option is the one I’m looking for, but we’re at a loss as to why it’s not available on my devices, unless it’s because of the number of apps I have installed “overloading” the OS’ ability to display them.

![1685C415-15FC-4737-98ED-E123AEE71236](https://user-images.githubusercontent.com/28748/71143335-cda83d00-21df-11ea-901c-b2b204b724f6.png)

**Comment by terrychou** [comment] 2019-12-19 04:05
@mchalkley have you tried to tap the "More" item (at the end of the first row of items) to reveal the extra options? My "Open in iVim" lies in the "Suggestions" sections after I did that.

**Comment by furuki328** [comment] 2019-12-19 12:10
From Files app.
![image](https://user-images.githubusercontent.com/28430794/71172067-a9f9fb00-22a2-11ea-8b69-066940200916.png)

select "・・・"  その他 means more or others
Then scroll down. Upper side just "iVim" is found, but it is not "open in".
![image](https://user-images.githubusercontent.com/28430794/71172467-a9ae2f80-22a3-11ea-9d31-cc5492de6048.png)

Down scroll until I find "iVimで開く". That means "open in iVim".
![image](https://user-images.githubusercontent.com/28430794/71172338-46bc9880-22a3-11ea-9442-6ff878ccb5ce.png)

**Comment by mchalkley** [comment] 2019-12-19 13:15
Yes, that’s the issue, on my device: neither the “Open in iVim” nor the “Copy to iVim” options are present, even in the “...” (more) section - the only option I have says simply “iVim”.  They used to be there, because I used them all the time, but they’ve disappeared and I can’t figure out how to get them back.

**Comment by terrychou** [comment] 2019-12-20 02:35
Well, if that is the case, the cause probably is the "overloading" problem you talked about. 

You can use the `:idocuments` command instead for now, they are actually the same in essential.

I will make iVim adapt the new share sheet of iOS 13.

**Comment by terrychou** [comment] 2019-12-23 09:00
@mchalkley I did some following-up research:

1. Since an app update could be treated as a "re-install", did your update solve this problem?

2. I planned to add an Action Extension to do the file opening, but it turned out that way would be different from the "Open in ..." item (it would only copy the content of the file, rather than editing the file in place).

**Comment by mchalkley** [comment] 2019-12-23 12:03
@terrychou I really appreciate your continuing to look into this.  I was also hoping the App Store version install would “reset” the Share Sheet options and “Open in iVim” would appear in the “More” section, but it did not.

I have also been slowly deleting apps that I don’t use regularly, in the hopes that it will cause the option to reappear, but that hasn’t worked either, yet.  I guess my only option now is to completely remove iVim and reinstall it.

**Comment by ericweir** [comment] 2019-12-23 14:10
> On Dec 18, 2019, at 10:15 AM, Mark Chalkley <notifications@github.com> wrote:
> 
> Well, the only thing we’ve been able to confirm is that the “Open in iVim” option doesn’t appear on either of my iPads or my iPhone.

Unrelated question: How do you sync between different installations of iVim?

----------------------------------------
Eric Weir
Decatur, GA  USA
eeweir@bellsouth.net

"He is the Picasso of pettiness, the Shakespeare of shit."

- Nate White

**Comment by terrychou** [comment] 2019-12-24 23:57
@ericweir files under `Documents` should be backed up in iCloud, other files such as those for auto-restore are not, since they are device-specific anyway.

**Comment by mchalkley** [comment] 2020-01-05 18:53
@ericweir You’re correct that those files are automatically backed up to iCloud - at least, they certainly are in my case....

**Comment by mchalkley** [comment] 2020-01-05 19:24
@terrychou, in testing the latest TestFlight beta, using the Share Sheet share option does indeed copy the text to iVim, but I still have no way to edit the file in place, the functionality that the “Open in iVim” command is designed to provide.  I’m using Notebooks by Alfons Schmid as my base notes repository, and it offers separate “Open in” and “Share” functions.  If I use “Share” and pick iVim, I get the text of the file in iVim, but there’s no name associated with it, so I can’t write it back to the Notebooks app.  If I use Notebooks’ “Open in” iVim command, I get the same thing.  If, though, I use “Open in” and pick a different editor, like GoCoEdit, I get the text and the associate Notebooks app file name, so if I edit the file, save it, and return to Notebooks, the file has been modified.

Thanks again,

Mark

**Comment by ericweir** [comment] 2020-01-05 21:35
> On Jan 5, 2020, at 1:53 PM, Mark Chalkley <notifications@github.com> wrote:
> 
> @ericweir You’re correct that those files are automatically backed up to iCloud - at least, they certainly are in my case....

Thanks, Mark.

------------------------------------------------------------------------------------------
Eric Weir
Decatur, GA  USA
eeweir@bellsouth.net

“This permanent doubt, the deep source of science.”

- Carlo Rovelli

**Comment by terrychou** [comment] 2020-01-06 07:31
@mchalkley "open file and edit it in place" cannot be done with the share extension, I have tried to figure out a workaround but with no luck (the system limits the permission). If you want to edit-file-in-place in iVim, you need to use the "Open in iVim" item instead. However, yours disappears for some unknown reason as discussed above.

Even from the "Open in ..." menu you mentioned, the "iVim" item is still the "Share with iVim" one, rather than "Open in iVim", while the "GoCoEdit" item may probably its "Open in GoCoEdit" one.

I know it is kind of confusing. But the "Share with iVim" still has its own use cases. For example, you can share selected text from an app to iVim; or you can concatenate several files' content into one and edit it in iVim. As a result, I have decided not to remove it.

Apple provides a new Share Sheet design in iOS 13, but it doesn't provide a way for users to arrange items in it, sigh...

**Comment by mchalkley** [comment] 2020-01-06 13:59
@terrychou is it possible that iOS doesn’t treat TestFlight apps the same as App Store apps?  I’ve deleted over a dozen apps that were showing in the Share Sheet list, but iVim still isn’t coming up as a “Copy to iVim” or “Open in iVim” option.

**Comment by terrychou** [comment] 2020-01-07 01:11
@mchalkley there are some differences between the TestFlight and App Store apps, but I don’t think the Share Sheet part is included in those. After all, it is one functionality provided by the developer rather than mandated by Apple.

Because iVim hasn’t added support to Shortcuts so far, I think this is why it doesn’t show up in its app list.

**Comment by mchalkley** [comment] 2020-01-10 17:15
@terrychou just as an FYI, I managed to get the "Open in iVim" "Share sheet" functionality to show up.  I tried deleting apps several at a time until the list just basically went down to half a dozen, but that didn't work.  Then, I deleted iVim and reinstalled it, no change.  Finally, I ended up just resetting the entire device and starting over, which fixed it.  Talk about having to take the "brute force" approach...  Anyway, thanks very much for all of your efforts.

Mark

**Comment by terrychou** [comment] 2020-01-11 14:16
@mchalkley even though in a hard way, it is great to know that you managed to get "Open in iVim" item back. As I mentioned above, Apple really should provide a way for users to arrange the items in the Share Sheet.

**Comment by mchalkley** [comment] 2020-01-24 14:54
@terrychou, I have posted the Share Sheet issues in Apple's Feedback app, reported their handling of it as a bug, and put in a feature request that they allow users to arrange items for all installed apps, for what little it's probably worth.  Apple is one of those companies where things are great if you happen to agree 100% with their priorities, methods, UI, dev cycle, etc.  They certainly don't care about what anybody else thinks, at least not in the short term, and even the long term is debatable.  I'm running the iPadOS and iOS public betas, and every time there's an update, the Share Sheet gets reset and I have to uninstall and reinstall iVim to get the Open In functionality back.  On top of that, several times since getting it working I have installed a new app, or reinstalled one I had deleted to get it working, and that broke it again.  Anyway, I think you can close this one, because it's obviously an Apple problem...

**Closed** 2020-01-26 02:38 UTC

**Comment by mchalkley** [comment] 2020-01-28 19:58
@terrychou, I know I said this was working fine for me, but I just noticed that the Open in functionality appears Notebooks' Share Sheet for .md files, but not for .txt files.  Is there something that you need to do to "register" iVim to be "shareable" for .txt files, or is this just another iOS/iPadOS glitch?

**Comment by terrychou** [comment] 2020-01-29 01:45
@mchalkley I tried a .txt file, it worked for me. Actually, I “register” iVim in a way that it should open any type of file. I suggest that you really should try the `:idocuments` command.
